#!/usr/bin/env ruby
#^syntax detection

site 'https://supermarket.getchef.com/api/v1'

cookbook 'apt'
# cookbook 'build-essential'
cookbook 'nginx'
cookbook 'postgresql'
# cookbook 'git'

# cookbook 'chef-client'

# cookbook 'apache2', '>= 1.0.0'
cookbook 'rvm'
  # :git => 'https://github.com/fnichol/chef-rvm'

# cookbook 'postgresql',
#   :git => 'https://github.com/findsyou/cookbooks',
#   :ref => 'postgresql-improvements'
