#!/usr/bin/env ruby
#^syntax detection

# site 'http://community.opscode.com/api/v1'
site 'https://supermarket.getchef.com/api/v1'

cookbook 'apt', '~> 2.6.1'
cookbook 'nginx', '~> 2.7.4'
cookbook 'postgresql', '~> 3.4.14'
cookbook 'git', '~> 4.1.0'

# cookbook 'chef-client'

cookbook 'rvm', :git => 'git://github.com/fnichol/chef-rvm.git'

# cookbook 'postgresql',
#   :git => 'https://github.com/findsyou/cookbooks',
#   :ref => 'postgresql-improvements'
