#!/usr/bin/env ruby
#^syntax detection

site 'https://supermarket.getchef.com/api/v1'

cookbook 'apt', '~> 2.6.1'
cookbook 'build-essential', '~> 2.1.3'
cookbook 'nginx', '~> 2.7.4'
cookbook 'git', '~> 4.1.0'
cookbook 'postgresql', '~> 3.4.14'
cookbook 'database', '~> 2.3.1'
cookbook 'rvm', :git => 'git://github.com/fnichol/chef-rvm.git'

